title: ibericode
description: WordPress products for small businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ibericode.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title/

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
